CREATE TABLE foodTypes(
                          id int generated by default as identity NOT NULL,
                          name varchar NOT NULL,

                          primary key (id)
);

create table food(
    id int generated by default as identity NOT NULL,
    name varchar(255) NOT NULL,
    foodTypesId int NOT NULL,
    calories int NOT NULL,

    primary key (id),
    foreign key (foodTypesId) references foodTypes(id)
);

CREATE TABLE drinkTypes(
                           id int generated by default as identity NOT NULL,
                           name varchar NOT NULL,

                           primary key (id)
);

CREATE TABLE drinks(
    id int generated by default as identity NOT NULL,
    name varchar NOT NULL,
    drinkTypesId int NOT NULL,
    calories int NOT NULL,

    primary key (id),
    foreign key (drinkTypesId) references drinkTypes(id)
);