create table employee(
                          id int generated by default as identity,
                          name varchar(255),
                          email varchar(255),
                          primary key (id)
);